-- DM / Dameng demo schema for the Tabularis DM plugin.
--
-- Run this script while connected as the demo owner, for example DEV2.
-- Missing-object errors from the DROP statements are safe to ignore.

DROP VIEW V_PRODUCT_SALES;
DROP VIEW V_CUSTOMER_LIFETIME_VALUE;
DROP VIEW V_ORDER_DETAIL;
DROP VIEW V_ORDER_SUMMARY;

DROP PROCEDURE P_REFRESH_ORDER_STATS;
DROP FUNCTION FN_CUSTOMER_TOTAL_AMOUNT;
DROP FUNCTION FN_CUSTOMER_ORDER_COUNT;
DROP TRIGGER TRG_ORDERS_AUDIT;
DROP SEQUENCE ORDER_AUDIT_SEQ;

DROP TABLE ORDER_ITEMS;
DROP TABLE ORDER_AUDIT;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE CUSTOMERS;
DROP TABLE T_WRITE_TEST;
DROP TABLE T_LOB_TEST;
DROP TABLE T_DEFAULT_TEST;

CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    CITY VARCHAR(40),
    SEGMENT VARCHAR(30),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
    ID INT NOT NULL,
    SKU VARCHAR(40) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(40),
    PRICE DECIMAL(18, 2) NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
    ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    ORDER_NO VARCHAR(40) NOT NULL,
    STATUS VARCHAR(20),
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(18, 2),
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID)
);

CREATE TABLE ORDER_ITEMS (
    ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ID)
);

CREATE TABLE ORDER_AUDIT (
    ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    OLD_STATUS VARCHAR(20),
    NEW_STATUS VARCHAR(20),
    OLD_TOTAL_AMOUNT DECIMAL(18, 2),
    NEW_TOTAL_AMOUNT DECIMAL(18, 2),
    CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ORDER_AUDIT PRIMARY KEY (ID)
);

CREATE TABLE T_WRITE_TEST (
    ID INT IDENTITY(1,1) NOT NULL,
    NAME VARCHAR(80),
    SCORE INT,
    NOTE VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_T_WRITE_TEST PRIMARY KEY (ID)
);

CREATE TABLE T_LOB_TEST (
    ID INT IDENTITY(1,1) NOT NULL,
    NAME VARCHAR(80),
    PAYLOAD_BLOB BLOB,
    PAYLOAD_BIN VARBINARY(200),
    PAYLOAD_CLOB CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_T_LOB_TEST PRIMARY KEY (ID)
);

CREATE TABLE T_DEFAULT_TEST (
    ID INT IDENTITY(1,1) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'NEW' NOT NULL,
    SCORE INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_T_DEFAULT_TEST PRIMARY KEY (ID)
);

COMMENT ON TABLE CUSTOMERS IS 'Customer master data';
COMMENT ON COLUMN CUSTOMERS.ID IS 'Customer primary key';
COMMENT ON COLUMN CUSTOMERS.NAME IS 'Customer display name';
COMMENT ON COLUMN CUSTOMERS.CITY IS 'Customer city';
COMMENT ON COLUMN CUSTOMERS.SEGMENT IS 'Customer market segment';
COMMENT ON COLUMN CUSTOMERS.CREATED_AT IS 'Customer creation timestamp';

COMMENT ON TABLE ORDERS IS 'Customer order headers';
COMMENT ON COLUMN ORDERS.ID IS 'Order primary key';
COMMENT ON COLUMN ORDERS.CUSTOMER_ID IS 'Customer foreign key';
COMMENT ON COLUMN ORDERS.ORDER_NO IS 'Business order number';
COMMENT ON COLUMN ORDERS.STATUS IS 'Order workflow status';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS 'Order date';
COMMENT ON COLUMN ORDERS.TOTAL_AMOUNT IS 'Order total amount';

COMMENT ON TABLE T_WRITE_TEST IS 'Writable row editing smoke test table';
COMMENT ON COLUMN T_WRITE_TEST.ID IS 'Identity primary key';
COMMENT ON COLUMN T_WRITE_TEST.NAME IS 'Editable name';
COMMENT ON COLUMN T_WRITE_TEST.SCORE IS 'Editable numeric score';
COMMENT ON COLUMN T_WRITE_TEST.NOTE IS 'Editable note';
COMMENT ON COLUMN T_WRITE_TEST.CREATED_AT IS 'Creation timestamp';

COMMENT ON TABLE T_LOB_TEST IS 'LOB and binary write smoke test table';
COMMENT ON COLUMN T_LOB_TEST.ID IS 'Identity primary key';
COMMENT ON COLUMN T_LOB_TEST.PAYLOAD_BLOB IS 'Base64 BLOB payload';
COMMENT ON COLUMN T_LOB_TEST.PAYLOAD_BIN IS 'Base64 VARBINARY payload';
COMMENT ON COLUMN T_LOB_TEST.PAYLOAD_CLOB IS 'CLOB text payload';

COMMENT ON TABLE T_DEFAULT_TEST IS 'Default values and empty insert smoke test table';
COMMENT ON COLUMN T_DEFAULT_TEST.ID IS 'Identity primary key';
COMMENT ON COLUMN T_DEFAULT_TEST.STATUS IS 'Default status';
COMMENT ON COLUMN T_DEFAULT_TEST.SCORE IS 'Default numeric score';

CREATE SEQUENCE ORDER_AUDIT_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO CUSTOMERS (ID, NAME, CITY, SEGMENT) VALUES (1, 'Acme Retail', 'Shanghai', 'Retail');
INSERT INTO CUSTOMERS (ID, NAME, CITY, SEGMENT) VALUES (2, 'Northwind Trading', 'Beijing', 'Wholesale');
INSERT INTO CUSTOMERS (ID, NAME, CITY, SEGMENT) VALUES (3, 'Pearl Analytics', 'Shenzhen', 'Enterprise');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE) VALUES (1, 'DM-BOOK-001', 'DM Handbook', 'Books', 89.00);
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE) VALUES (2, 'TB-PLG-001', 'Plugin Support Pack', 'Software', 199.00);
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY, PRICE) VALUES (3, 'TB-OPS-001', 'Ops Dashboard Kit', 'Software', 399.00);

INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NO, STATUS, ORDER_DATE, TOTAL_AMOUNT)
VALUES (1, 1, 'ORD-2026-0001', 'PAID', DATE '2026-06-01', 467.00);
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NO, STATUS, ORDER_DATE, TOTAL_AMOUNT)
VALUES (2, 2, 'ORD-2026-0002', 'PENDING', DATE '2026-06-03', 129.00);
INSERT INTO ORDERS (ID, CUSTOMER_ID, ORDER_NO, STATUS, ORDER_DATE, TOTAL_AMOUNT)
VALUES (3, 3, 'ORD-2026-0003', 'PAID', DATE '2026-06-05', 798.00);

INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (1, 1, 1, 3, 89.00);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (2, 1, 2, 1, 200.00);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (3, 2, 1, 1, 129.00);
INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (4, 3, 3, 2, 399.00);

INSERT INTO T_WRITE_TEST (NAME, SCORE, NOTE) VALUES ('Seed Alpha', 10, 'Editable demo row');
INSERT INTO T_WRITE_TEST (NAME, SCORE, NOTE) VALUES ('Seed Beta', 20, 'Try inline update/delete');
INSERT INTO T_LOB_TEST (NAME, PAYLOAD_BLOB, PAYLOAD_BIN, PAYLOAD_CLOB)
VALUES ('Seed LOB', HEXTORAW('6869'), HEXTORAW('6869'), 'Seed CLOB text');
INSERT INTO T_DEFAULT_TEST (STATUS) VALUES ('READY');

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);
ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);
ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS(PRODUCT_ID);
CREATE UNIQUE INDEX UX_PRODUCTS_SKU ON PRODUCTS(SKU);
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY);

CREATE OR REPLACE VIEW V_ORDER_SUMMARY AS
SELECT
    o.ID AS ORDER_ID,
    c.NAME AS CUSTOMER_NAME,
    o.STATUS,
    o.TOTAL_AMOUNT
FROM ORDERS o
JOIN CUSTOMERS c ON c.ID = o.CUSTOMER_ID;

CREATE OR REPLACE VIEW V_ORDER_DETAIL AS
SELECT
    o.ID AS ORDER_ID,
    o.ORDER_NO,
    o.STATUS,
    o.ORDER_DATE,
    c.ID AS CUSTOMER_ID,
    c.NAME AS CUSTOMER_NAME,
    p.ID AS PRODUCT_ID,
    p.SKU,
    p.NAME AS PRODUCT_NAME,
    oi.QUANTITY,
    oi.UNIT_PRICE,
    oi.QUANTITY * oi.UNIT_PRICE AS LINE_AMOUNT
FROM ORDERS o
JOIN CUSTOMERS c ON c.ID = o.CUSTOMER_ID
JOIN ORDER_ITEMS oi ON oi.ORDER_ID = o.ID
JOIN PRODUCTS p ON p.ID = oi.PRODUCT_ID;

CREATE OR REPLACE VIEW V_CUSTOMER_LIFETIME_VALUE AS
SELECT
    c.ID AS CUSTOMER_ID,
    c.NAME AS CUSTOMER_NAME,
    COUNT(DISTINCT o.ID) AS ORDER_COUNT,
    COALESCE(SUM(o.TOTAL_AMOUNT), 0) AS TOTAL_AMOUNT
FROM CUSTOMERS c
LEFT JOIN ORDERS o ON o.CUSTOMER_ID = c.ID
GROUP BY c.ID, c.NAME;

CREATE OR REPLACE VIEW V_PRODUCT_SALES AS
SELECT
    p.ID AS PRODUCT_ID,
    p.SKU,
    p.NAME AS PRODUCT_NAME,
    COALESCE(SUM(oi.QUANTITY), 0) AS TOTAL_QUANTITY,
    COALESCE(SUM(oi.QUANTITY * oi.UNIT_PRICE), 0) AS TOTAL_AMOUNT
FROM PRODUCTS p
LEFT JOIN ORDER_ITEMS oi ON oi.PRODUCT_ID = p.ID
GROUP BY p.ID, p.SKU, p.NAME;

CREATE OR REPLACE FUNCTION FN_CUSTOMER_ORDER_COUNT(P_CUSTOMER_ID INT) RETURN INT AS
    V_COUNT INT;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM ORDERS WHERE CUSTOMER_ID = P_CUSTOMER_ID;
    RETURN V_COUNT;
END;
/

CREATE OR REPLACE FUNCTION FN_CUSTOMER_TOTAL_AMOUNT(P_CUSTOMER_ID INT) RETURN DECIMAL(18, 2) AS
    V_TOTAL DECIMAL(18, 2);
BEGIN
    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) INTO V_TOTAL FROM ORDERS WHERE CUSTOMER_ID = P_CUSTOMER_ID;
    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE PROCEDURE P_REFRESH_ORDER_STATS AS
BEGIN
    NULL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDERS_AUDIT
AFTER UPDATE OF STATUS, TOTAL_AMOUNT ON ORDERS
FOR EACH ROW
BEGIN
    INSERT INTO ORDER_AUDIT (
        ID,
        ORDER_ID,
        OLD_STATUS,
        NEW_STATUS,
        OLD_TOTAL_AMOUNT,
        NEW_TOTAL_AMOUNT
    ) VALUES (
        ORDER_AUDIT_SEQ.NEXTVAL,
        :OLD.ID,
        :OLD.STATUS,
        :NEW.STATUS,
        :OLD.TOTAL_AMOUNT,
        :NEW.TOTAL_AMOUNT
    );
END;
/

COMMIT;
